_wandb:
    value:
        cli_version: 0.26.1
        e:
            vq8167s6f80khqir1qhybyb3hosrbpjw:
                apple:
                    ecpuCores: 4
                    gpuCores: 7
                    macModel: MacBookAir10,1
                    memoryGb: 8
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "6442450944"
                codePath: train_gru.py
                codePathLocal: train_gru.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "234301390848"
                email: yjm5439@snu.ac.kr
                executable: /opt/anaconda3/envs/DACON-2605/bin/python
                git:
                    commit: 4a837ab9a0bc0933f54d044db42e63146f0a2e08
                    remote: https://github.com/dropyoon/Mosquito-Flight-Trajectory-Prediction.git
                host: yunjimin-ui-MacBookAir.local
                memory:
                    total: "8589934592"
                os: macOS-26.4.1-arm64-arm-64bit
                program: /Users/yoonjimin/Desktop/대학교/3-1/모기/open/Mosquito-Flight-Trajectory-Prediction/train_gru.py
                python: CPython 3.10.20
                root: /Users/yoonjimin/Desktop/대학교/3-1/모기/open/Mosquito-Flight-Trajectory-Prediction
                startedAt: "2026-05-08T07:28:13.354812Z"
                writerId: vq8167s6f80khqir1qhybyb3hosrbpjw
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 16
                - 62
            "4": 3.10.20
            "5": 0.26.1
            "12": 0.26.1
            "13": darwin-arm64
batch_size:
    value: 128
device:
    value: mps
epochs:
    value: 100
hidden_size:
    value: 64
input_size:
    value: 3
lr:
    value: 0.0001
model:
    value: GRU
num_layers:
    value: 2
output_size:
    value: 3
