_wandb:
    value:
        cli_version: 0.26.1
        e:
            pfxho3gzwmcjp2juljazu5r8uruniivn:
                codePath: train_gru.py
                codePathLocal: train_gru.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.3"
                disk:
                    /:
                        total: "997713768448"
                        used: "773475381248"
                email: haiyanai03@gmail.com
                executable: C:\Users\haiya\anaconda3\envs\DACON-2605\python.exe
                git:
                    commit: fa493176ef2194beec159641ccdc4cb00ac988f4
                    remote: https://github.com/ki-menu/Mosquito-Flight-Trajectory-Prediction.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-2e546c1f-7ce3-21cc-ae97-33952d6e048f
                host: kimenu
                memory:
                    total: "16935870464"
                os: Windows-10-10.0.26200-SP0
                program: C:\Users\haiya\kimenu\DACON\Mosquito flight trajectory\train_gru.py
                python: CPython 3.10.20
                root: C:\Users\haiya\kimenu\DACON\Mosquito flight trajectory
                startedAt: "2026-05-08T02:58:14.135075Z"
                writerId: pfxho3gzwmcjp2juljazu5r8uruniivn
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.10.20
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 300
hidden_size:
    value: 64
input_size:
    value: 3
lr:
    value: 0.001
num_layers:
    value: 2
weight_decay:
    value: 0.0001
